= Production First

== A story of production last 
One of our last projects went to production like follows.

* Download the trial of the new product
* Make it https://blog.codinghorror.com/the-works-on-my-machine-certification-program/[work on my machine]
* Ramp up a team ( start with team lead & analysts )
* Write specifications
* Onboard developers
* Order a test environment at operations department
* Release engineer interviews developer & manually configures test environment
* Order an integration environment
* Release engineer manually configures integration environment with some optimisations
* We notice that there are subtile differences between the environments causing misbehaviour of the product
* Onboard release manager
* Order a acceptance environment
* Release engineer manually configures integration environment, release manager takes notes into a deployment checklist spread sheet, so we can reproduce for production
* Order a production environment which is delivered 2 days before go live
* Going through the deployment checklist spread sheet takes ~2h and we did not have time for rehearsal, so engineers say there is a 25% chance it won't work
* Plan production rollout after office hours, organise on call duty, pizza & beer for the release party starting @ 10pm
* The deployment checklist spread sheet describing a worst case manual deployment is made the official deployment manual 
* Release manager & engineer are full time members of the team to organise the quarterly late night deployments with communication-, escalation- and roll back plan 

The whole process took months and has obvious flaws.

* Bad practice has become the standard process
* Time to production is too long. This also increases time to fix bugs and thus makes roll back plans necessary. 
* Deployment is automated through continuous improvement cycles if at all. Error prone, expensive manual interaction is the starting point. 

== Production first

With production first we flip this process 180° around.

* Automate deployment to production before implementing any feature with business value : https://en.wikipedia.org/wiki/%22Hello,_World!%22_program[Hello World] is the https://en.wikipedia.org/wiki/Minimum_viable_product[minimal viable product] and your fist deployment to production is naturally a https://openpracticelibrary.com/practice/dark-launches/[dark launch] 
* Introduce automated regression and acceptance testing
* Keep slow pipelines failing
* Only introduce manual approval for production if required by regulations




